const imgPath = '../../src/img/';
import {IMG_PATH} from "../consts/constants";

const productList = [
    {
        id: 1,
        name: 'Бальмунг',
        photo: IMG_PATH + 'Balmung.png',
        classArtifact: 'Weapon',
        cost: '200',
        oldCost: '250',
        quantity: '4',
        promotion: 'true',
        rating: '9',
        origin: 'германо-скандинавская мифологиия',
        typeArtifact: 'боевой',
        formArtifact: 'меч',
        effect: 'игнорирование прочности',
        description: 'Однажды Зигфрид встретил под горой двух королей Нибелунгов: Шильбунга и Нибелунга, ' +
            'которые делили клад, когда-то зарытый ими. Короли предложили Зигфриду поделить его между ними, ' +
            'а в награду они бы дали ему «Меч Нибелунгов». Зигфрид поделил клад, но братья короли остались ' +
            'недовольны дележом. Расправиться с Зигфридом они призвали двенадцать великанов, но Зигфрид тут же ' +
            'отсек им головы Бальмунгом, а затем, перебив семьсот Нибелунгов, поразил двух братьев королей и ' +
            'победил могучего карлика Альбриха, который поклялся быть ему верным слугой.',
        bladeLength: '140',
        typeUse: 'рубящий',
        weight: '3400',
        user: 'Зигфрид, Хаген',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 2,
        name: 'Дюрандаль',
        photo: IMG_PATH + 'Durandal.png',
        classArtifact: 'Weapon',
        cost: '220',
        oldCost: 'undefined',
        quantity: '1',
        promotion: 'false',
        rating: '6',
        origin: 'французские средневековые легенды',
        typeArtifact: 'боевой',
        formArtifact: 'меч',
        effect: 'не тупится',
        description: 'Выкован кузнецом Галаном (или по другим сказаниям — кузнецом Мадельгером из Регенсбурга, ' +
            'Мунификаном). Вручён Карлом Великим своему рыцарю после принесения им присяги. В рукояти мощехранилище ' +
            '(кровь св. Василия, нетленный зуб св. Петра, власы Дионисия Парижского, Божия человека, обрывок ризы ' +
            'Приснодевы Марии).',
        bladeLength: '120',
        typeUse: 'рубящий',
        weight: '3000',
        user: 'Карл Великий, Роланд',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 3,
        name: 'Каладболг',
        photo: IMG_PATH + 'Kaladbold.png',
        classArtifact: 'Weapon',
        cost: '230',
        oldCost: 'undefined',
        quantity: '5',
        promotion: 'false',
        rating: '6',
        origin: 'ирландские легенды',
        typeArtifact: 'боевой, усиливающий',
        formArtifact: 'меч',
        effect: 'увеличивает силу',
        description: 'Отождествляется с Экскалибуром более позднего времени. Обладает достаточной силой, чтобы ' +
            'срезать три холма.',
        bladeLength: '110',
        typeUse: 'рубящий',
        weight: '4500',
        user: 'Фергус',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 4,
        name: 'Меч-кладенец',
        photo: IMG_PATH + 'SwordKladenets.png',
        classArtifact: 'Weapon',
        cost: '400',
        oldCost: 'undefined',
        quantity: '32',
        promotion: 'false',
        rating: '7',
        origin: 'русский фольклор',
        typeArtifact: 'боевой, усиливающий',
        formArtifact: 'меч',
        effect: 'игнорирование неуязвимости',
        description: 'Меч–кладенец, помощник мужественных героев многих русских сказок, мечта любого воина. Если ' +
            'верить старинным легендам это оружие помогает победить в любом бою. Его использовали многие знаменитые ' +
            'богатыри из русских былин. Только таким мечом можно победить большинство сказочных чудовищ и злодеев, ' +
            'которые для других видов оружия остаются неуязвимыми.',
        bladeLength: '160',
        typeUse: 'рубящий',
        weight: '4800',
        user: 'Князь Олег Вещий, Святогор, Илья Муромец, Добрыня Никитич, Иван Царевич, и пр.',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 5,
        name: 'Экскалибур',
        photo: IMG_PATH + 'Excalibur.png',
        classArtifact: 'Weapon',
        cost: '360',
        oldCost: 'undefined',
        quantity: '2',
        promotion: 'false',
        rating: '7',
        origin: 'британские мифы',
        typeArtifact: 'боевой, усиливающий',
        formArtifact: 'меч',
        effect: 'игнорирование прочности',
        description: 'Легендарный меч короля Артура, которому часто приписываются мистические и волшебные свойства. ' +
            'Его ножны останавливают кровотечение.',
        bladeLength: '120',
        typeUse: 'рубящий',
        weight: '2000',
        user: 'король Артур',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 6,
        name: 'Гламдринг',
        photo: IMG_PATH + 'Glamdring.png',
        classArtifact: 'Weapon',
        cost: '275',
        oldCost: 'undefined',
        quantity: '0',
        promotion: 'false',
        rating: '8',
        origin: 'Дж. Р. Р. Толкин',
        typeArtifact: 'боевой',
        formArtifact: 'меч',
        effect: 'светится',
        description: 'Гламдринг в переводе с синдарина означает «Молотящий врагов». Гоблины называют его просто ' +
            '«Колотун», но уточнено, что корень glam означает не «враг» («враги), а «орк» («орки»). Как и все ' +
            'мечи эльфийской работы, Гламдринг светится синим или белым огнём, если орки находятся рядом.',
        bladeLength: '130',
        typeUse: 'рубяще-колющий',
        weight: '1800',
        user: 'Гондолин Тургон, Гэндальф',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 7,
        name: 'Тоцука-но цуруги',
        photo: IMG_PATH + 'TocukaNoCurugi.png',
        classArtifact: 'Weapon',
        cost: '190',
        oldCost: 'undefined',
        quantity: '3',
        promotion: 'false',
        rating: '6',
        origin: 'японская мифология',
        typeArtifact: 'боевой',
        formArtifact: 'меч',
        effect: 'игнорирование божественности',
        description: 'Этим мечом Сусаноо отрубил все головы и хвосты Ямата-но ороти(восьмиглавый и восьмихвостый ' +
            'великий змей). Кроме этого, меч был использован Идзанаги(в синтоизме бог творения) для убийства ' +
            'бога Огня.',
        bladeLength: '120',
        typeUse: 'рубящий',
        weight: '1800',
        user: 'бог Ветра Сусаноо',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 8,
        name: 'Копьё Афины',
        photo: IMG_PATH + 'AthenaSpear.png',
        classArtifact: 'Weapon',
        cost: '150',
        oldCost: '190',
        quantity: '6',
        promotion: 'true',
        rating: '5',
        origin: 'древнегреческая мифология',
        typeArtifact: 'боевой',
        formArtifact: 'копье',
        effect: 'неизветно',
        description: 'От его удара об землю при споре с Посейдоном за владычество над будущим городом Афины ' +
            'выросла первая олива.',
        bladeLength: 'колющий',
        typeUse: '2500',
        weight: 'undefined',
        user: 'Афина',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 9,
        name: 'Копьё Гора',
        photo: IMG_PATH + 'GorSpear.png',
        classArtifact: 'Weapon',
        cost: '135',
        oldCost: 'undefined',
        quantity: '8',
        promotion: 'false',
        rating: '4',
        origin: 'древнеегипетская мифология',
        typeArtifact: 'боевой',
        formArtifact: 'копье',
        effect: 'неизветно',
        description: 'Копьё, которое благословила богиня Нейт. С божественным оружием Гор, которого называют ' +
            'также «гарпунщиком», преследует тифонические силы в образе бегемотов. Для защиты на пути в ' +
            'потусторонний мир мертвым дают с собой маленькие фигурки копий.',
        bladeLength: 'undefined',
        typeUse: 'колющий',
        weight: '1800',
        user: 'Гор',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 10,
        name: 'Гунгнир',
        photo: IMG_PATH + 'Gugnir.png',
        classArtifact: 'Weapon',
        cost: '320',
        oldCost: 'undefined',
        quantity: '7',
        promotion: 'false',
        rating: '6',
        origin: 'германо-скандинавская мифология',
        typeArtifact: 'боевой, усиливающий',
        formArtifact: 'копье',
        effect: 'игнорирование прочности',
        description: 'Обладает волшебным свойством поражать любую цель, пробивая самые толстые щиты и панцири и ' +
            'разбивая на куски самые закалённые мечи.',
        bladeLength: 'undefined',
        typeUse: 'колющий',
        weight: '3300',
        user: 'Один',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 11,
        name: 'Карр Белаиг Дургин',
        photo: IMG_PATH + 'KarrBelaigDurgin.png',
        classArtifact: 'Weapon',
        cost: '175',
        oldCost: 'undefined',
        quantity: '5',
        promotion: 'false',
        rating: '3',
        origin: 'кельтская мифология',
        typeArtifact: 'боевой',
        formArtifact: 'копье',
        effect: 'собственная воля',
        description: 'Может убивать по собственной воле (по другой версии, убивает благодаря контролю над ним ' +
            'демона, убивавшего всех, кто пробовал пройти, не предложив приношение («Aided Máelodrán meic ' +
            'Dímma Chróin»)).',
        bladeLength: 'undefined',
        typeUse: 'колющий',
        weight: '3100',
        user: 'Маэлодран',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 12,
        name: 'Трезубец Посейдона',
        photo: IMG_PATH + 'PoseidonTrident.png',
        classArtifact: 'Weapon',
        cost: '410',
        oldCost: '420',
        quantity: '3',
        promotion: 'true',
        rating: '6',
        origin: 'древнегреческая мифология',
        typeArtifact: 'боевой',
        formArtifact: 'трезубец',
        effect: 'магия',
        description: 'Вызывает землетрясения и порождает лошадей своим ударом о твердь. Сделан киклопами. Символ ' +
            'морской стихии, грома и бури.',
        bladeLength: 'undefined',
        typeUse: 'магический',
        weight: '7600',
        user: 'Посейдон',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 13,
        name: 'Ваджра',
        photo: IMG_PATH + 'Vajra.png',
        classArtifact: 'Weapon',
        cost: '600',
        oldCost: 'undefined',
        quantity: '12',
        promotion: 'false',
        rating: '8',
        origin: 'Индийская мифология и буддизм',
        typeArtifact: 'боевой',
        formArtifact: 'трезубец',
        effect: 'магия',
        description: 'Это мощное оружие, соединяющее в себе свойства меча, булавы и копья. Имеет символическую ' +
            'аналогию с алмазом — может резать что угодно, но не сам себя — и с молнией — непреодолимая сила. ' +
            'Возможности ваджры непредсказуемы: если ей сражается громовержец, то это просто мощное наступательное ' +
            'оружие, а если кто-то из буддистского пантеона — от них можно ожидать любой восточной магии.',
        bladeLength: 'undefined',
        typeUse: 'магический, психологический',
        weight: '800',
        user: 'Индра',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 14,
        name: 'Мьёльнир',
        photo: IMG_PATH + 'Mjolnir.png',
        classArtifact: 'Weapon',
        cost: '480',
        oldCost: '550',
        quantity: '8',
        promotion: 'true',
        rating: '9',
        origin: 'германо-скандинавская мифология',
        typeArtifact: 'боевой',
        formArtifact: 'молот',
        effect: 'гром и молния',
        description: 'Молот может становился метательным оружием, которое всегда поражает цель и возвращается ' +
            'обратно в руки метателя. Он настолько мощное оружие, что его удар вызывает молнии и гром. Мьёльнир ' +
            'способен не только убивать, но и оживлять',
        bladeLength: 'undefined',
        typeUse: 'ударный',
        weight: 'undefined',
        user: 'Тор',
        category: 'undefined',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 15,
        name: 'Бабр-е Байан',
        photo: IMG_PATH + 'BabrEBayan.png',
        classArtifact: 'Armor',
        cost: '230',
        oldCost: 'undefined',
        quantity: '4',
        promotion: 'false',
        rating: '7',
        origin: 'персидский народный эпос',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'частичная неуязвимость',
        description: 'Непроницаем для оружия, огня и воды.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '27500',
        user: 'Рустам',
        category: 'торс, шлем, поножи, перчатки',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 16,
        name: 'панцирь Ахилла',
        photo: IMG_PATH + 'Ahill.png',
        classArtifact: 'Armor',
        cost: '60',
        oldCost: 'undefined',
        quantity: '12',
        promotion: 'false',
        rating: '5',
        origin: 'героические сказания древних греков',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'нет',
        description: 'Доспехи, скованные искусной рукой самого Гефеста.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '10000',
        user: 'Ахилл',
        category: 'торс',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 17,
        name: 'шлем Ахилла',
        photo: IMG_PATH + 'Ahill.png',
        classArtifact: 'Armor',
        cost: '40',
        oldCost: 'undefined',
        quantity: '16',
        promotion: 'false',
        rating: '5',
        origin: 'героические сказания древних греков',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'нет',
        description: 'Доспехи, скованные искусной рукой самого Гефеста.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '2500',
        user: 'Ахилл',
        category: 'шлем',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 18,
        name: 'поножи Ахилла',
        photo: IMG_PATH + 'Ahill.png',
        classArtifact: 'Armor',
        cost: '30',
        oldCost: 'undefined',
        quantity: '14',
        promotion: 'false',
        rating: '5',
        origin: 'героические сказания древних греков',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'нет',
        description: 'Доспехи, скованные искусной рукой самого Гефеста.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '1600',
        user: 'Ахилл',
        category: 'поножи',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 19,
        name: 'щит Ахилла',
        photo: IMG_PATH + 'Ahill.png',
        classArtifact: 'Armor',
        cost: '50',
        oldCost: 'undefined',
        quantity: '22',
        promotion: 'false',
        rating: '5',
        origin: 'героические сказания древних греков',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'нет',
        description: 'Доспехи, скованные искусной рукой самого Гефеста.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '6600',
        user: 'Ахилл',
        category: 'щит',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 20,
        name: 'Мегин-гьорд',
        photo: IMG_PATH + 'Tor.png',
        classArtifact: 'Armor',
        cost: '80',
        oldCost: '95',
        quantity: '9',
        promotion: 'true',
        rating: '6',
        origin: 'скандинавская мифология',
        typeArtifact: 'усиливающий',
        formArtifact: 'доспех',
        effect: 'увеличивает силу',
        description: 'Является частью доспеха Тора, увеличивает силу вдвое.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '800',
        user: 'Тор',
        category: 'пояс',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 21,
        name: 'Иарнгрейпер',
        photo: IMG_PATH + 'Tor.png',
        classArtifact: 'Armor',
        cost: '50',
        oldCost: 'undefined',
        quantity: '13',
        promotion: 'false',
        rating: '7',
        origin: 'скандинавская мифология',
        typeArtifact: 'специальный',
        formArtifact: 'доспех',
        effect: 'удерживание Мьёльнира',
        description: 'Железные рукавицы, без которых нельзя удержать рукоять раскалённого докрасна молота Мьёльнира',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '2300',
        user: 'Тор',
        category: 'перчатки',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 22,
        name: 'Таларии',
        photo: IMG_PATH + 'Talarii.png',
        classArtifact: 'Armor',
        cost: '180',
        oldCost: 'undefined',
        quantity: '18',
        promotion: 'false',
        rating: '10',
        origin: 'древнегреческая мифология',
        typeArtifact: 'специальный',
        formArtifact: 'доспех',
        effect: 'полет',
        description: 'Дают возможность подниматься в воздух.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '200',
        user: 'Гермес',
        category: 'обувь',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 23,
        name: 'Сапоги-скороходы',
        photo: IMG_PATH + 'SevenLeagueBoots.png',
        classArtifact: 'Armor',
        cost: '120',
        oldCost: '140',
        quantity: '6',
        promotion: 'true',
        rating: '9',
        origin: 'славянские сказки',
        typeArtifact: 'специальный',
        formArtifact: 'доспех',
        effect: 'скорость',
        description: 'Надевший сапоги получает способность передвигаться с большой скоростью: каждый сделанный ' +
            'шаг переносит владельца сапог на значительное расстояние (отсюда «семимильные», то есть как вариант, ' +
            'каждый шаг равняется семи милям).',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '600',
        user: 'undefined',
        category: 'обувь',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 24,
        name: 'Пояс Афродиты',
        photo: IMG_PATH + 'AphroditeBelt.png',
        classArtifact: 'Armor',
        cost: '90',
        oldCost: 'undefined',
        quantity: '66',
        promotion: 'false',
        rating: '8',
        origin: 'греческая мифология',
        typeArtifact: 'специальный',
        formArtifact: 'доспех',
        effect: 'увеличивает привлекательность',
        description: 'могущественный атрибут богини любви и красоты. Этот пояс обладает силой наделять того, кто ' +
            'его наденет, необычайной сексуальной привлекательностью.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '150',
        user: 'Афродита',
        category: 'пояс',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 25,
        name: 'Шапочка из фольги',
        photo: IMG_PATH + 'FoilHat.png',
        classArtifact: 'Armor',
        cost: '10',
        oldCost: 'undefined',
        quantity: '120',
        promotion: 'false',
        rating: '2',
        origin: 'современность',
        typeArtifact: 'специальный',
        formArtifact: 'доспех',
        effect: 'защищает мозг и сознание от вредных излучений и влияний',
        description: 'Некоторые люди верят в способность шапочек из фольги и других подобных устройств останавливать ' +
            'голоса в их головах и/или не позволять правительственным организациям, спецслужбам, инопланетянам, ' +
            'космическим лучам или сверхъестественным силам управлять сознанием против их воли. Эти люди полагают, ' +
            'что фольга отражает управляющие сигналы (например, от HAARP), передаваемые через внечувственное ' +
            'восприятие или через микроволновый слуховой эффект.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '100',
        user: '...',
        category: 'шлем',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 26,
        name: 'Кольчуга из митриля',
        photo: IMG_PATH + 'MithrilMail.png',
        classArtifact: 'Armor',
        cost: '500',
        oldCost: 'undefined',
        quantity: '8',
        promotion: 'false',
        rating: '7',
        origin: 'Дж. Р. Р. Толкин',
        typeArtifact: 'защитный',
        formArtifact: 'доспех',
        effect: 'неразрушимо',
        description: 'Невероятная лёгкость в сочетании с невероятной прочностью и благородным блеском.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: '400',
        user: 'Бильбо Бэггинс, Фродо Бэггинс',
        category: 'торс',
        typeMagic: 'undefined',
        level: 'undefined',
        impactType: 'undefined'
    },
    {
        id: 27,
        name: 'Щит',
        photo: IMG_PATH + 'Svitok1Earth.png',
        classArtifact: 'Spell',
        cost: '5',
        oldCost: 'undefined',
        quantity: '50',
        promotion: 'false',
        rating: '9',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Союзники получают меньше урона от рукопашных атак',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'земли',
        level: '1',
        impactType: 'защитный'
    },
    {
        id: 28,
        name: 'Зыбучий песок',
        photo: IMG_PATH + 'Svitok2Earth.png',
        classArtifact: 'Spell',
        cost: '8',
        oldCost: 'undefined',
        quantity: '25',
        promotion: 'false',
        rating: '3',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Появляются песчаные ловушки, останавливающие после прикосновения к ним.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'земли',
        level: '2',
        impactType: 'ловушка'
    },
    {
        id: 29,
        name: 'Защита от земли',
        photo: IMG_PATH + 'Svitok3Earth.png',
        classArtifact: 'Spell',
        cost: '12',
        oldCost: 'undefined',
        quantity: '38',
        promotion: 'false',
        rating: '4',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Уменьшает урон от заклинаний магии Земли',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'земли',
        level: '3',
        impactType: 'защитный'
    },
    {
        id: 30,
        name: 'Метеоритный дождь',
        photo: IMG_PATH + 'Svitok4Earth.png',
        classArtifact: 'Spell',
        cost: '16',
        oldCost: '23',
        quantity: '14',
        promotion: 'true',
        rating: '8',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Наносит урон камнями в небольшом радиусе',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'земли',
        level: '4',
        impactType: 'атакующий'
    },
    {
        id: 31,
        name: 'Лечение',
        photo: IMG_PATH + 'Svitok1Water.png',
        classArtifact: 'Spell',
        cost: '6',
        oldCost: 'undefined',
        quantity: '89',
        promotion: 'false',
        rating: '10',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Снимает действие всех негативных заклинаний и лечит',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воды',
        level: '1',
        impactType: 'защитный'
    },
    {
        id: 32,
        name: 'Ледяная Молния',
        photo: IMG_PATH + 'Svitok2Water.png',
        classArtifact: 'Spell',
        cost: '8',
        oldCost: '10',
        quantity: '55',
        promotion: 'true',
        rating: '8',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Наносит урон льдом',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воды',
        level: '2',
        impactType: 'атакующий'
    },
    {
        id: 33,
        name: 'Кольцо Холода',
        photo: IMG_PATH + 'Svitok3Water.png',
        classArtifact: 'Spell',
        cost: '12',
        oldCost: 'undefined',
        quantity: '24',
        promotion: 'false',
        rating: '7',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Наносит урон в небольшом радиусе исключая центр',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воды',
        level: '3',
        impactType: 'атакующий'
    },
    {
        id: 34,
        name: 'Клон',
        photo: IMG_PATH + 'Svitok4Water.png',
        classArtifact: 'Spell',
        cost: '24',
        oldCost: 'undefined',
        quantity: '8',
        promotion: 'false',
        rating: '7',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Создает клон, который разрушается от любого воздействия',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воды',
        level: '4',
        impactType: 'ловушка'
    },
    {
        id: 35,
        name: 'Защита от Огня',
        photo: IMG_PATH + 'Svitok1Fire.png',
        classArtifact: 'Spell',
        cost: '5',
        oldCost: 'undefined',
        quantity: '42',
        promotion: 'false',
        rating: '6',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Уменьшает урон от магии Огня',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'огня',
        level: '1',
        impactType: 'защитный'
    },
    {
        id: 36,
        name: 'Стена Огня',
        photo: IMG_PATH + 'Svitok2Fire.png',
        classArtifact: 'Spell',
        cost: '8',
        oldCost: 'undefined',
        quantity: '31',
        promotion: 'false',
        rating: '5',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Создает небольшую стену огня, проход через которую, наносит урон',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'огня',
        level: '2',
        impactType: 'атакующий'
    },
    {
        id: 37,
        name: 'Огненный шар',
        photo: IMG_PATH + 'Svitok3Fire.png',
        classArtifact: 'Spell',
        cost: '15',
        oldCost: '18',
        quantity: '47',
        promotion: 'true',
        rating: '7',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Урон огнём',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'огня',
        level: '3',
        impactType: 'атакующий'
    },
    {
        id: 38,
        name: 'Огненный щит',
        photo: IMG_PATH + 'Svitok4Fire.png',
        classArtifact: 'Spell',
        cost: '16',
        oldCost: 'undefined',
        quantity: '1',
        promotion: 'false',
        rating: '8',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Отражает часть нанесенного урона атакующему в ближнем бою',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'огня',
        level: '4',
        impactType: 'ловушка'
    },
    {
        id: 39,
        name: 'Ускорение',
        photo: IMG_PATH + 'Svitok1Air.png',
        classArtifact: 'Spell',
        cost: '6',
        oldCost: 'undefined',
        quantity: '53',
        promotion: 'false',
        rating: '9',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Увеличивает скорость',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воздуха',
        level: '1',
        impactType: 'усиление'
    },
    {
        id: 40,
        name: 'Точность',
        photo: IMG_PATH + 'Svitok2Air.png',
        classArtifact: 'Spell',
        cost: '8',
        oldCost: '11',
        quantity: '26',
        promotion: 'true',
        rating: '7',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Увеличивает атаку стреляющего при стрельбе(не распространяется на ближний бой).',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воздуха',
        level: '2',
        impactType: 'усиление'
    },
    {
        id: 41,
        name: 'Воздушный щит',
        photo: IMG_PATH + 'Svitok3Air.png',
        classArtifact: 'Spell',
        cost: '12',
        oldCost: 'undefined',
        quantity: '14',
        promotion: 'false',
        rating: '6',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Уменьшает урон, получаемый от дальних атак',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воздуха',
        level: '3',
        impactType: 'защитный'
    },
    {
        id: 42,
        name: 'Цепная молния',
        photo: IMG_PATH + 'Svitok4Air.png',
        classArtifact: 'Spell',
        cost: '24',
        oldCost: 'undefined',
        quantity: '36',
        promotion: 'false',
        rating: '10',
        origin: 'Heroes of Might and Magic III',
        typeArtifact: 'заклинание',
        formArtifact: 'свиток',
        effect: 'магия',
        description: 'Наносит урон четверым близко стоящим.',
        bladeLength: 'undefined',
        typeUse: 'undefined',
        weight: 'undefined',
        user: 'undefined',
        category: 'undefined',
        typeMagic: 'воздуха',
        level: '4',
        impactType: 'атакующий'
    }
];

export default productList